---
- name: Include architecture specific
  include: "{{ ansible_architecture }}.yml"

- name: Include for centos 7
  include: install_centos_7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


